import { Activity, Files, Network, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useState } from "react";

import MetricCard from "../components/ui/MetricCard";
import { compliance, documentStats, maintenanceCatalog, patterns } from "../services/api";

export default function Dashboard() {
  const [summary,setSummary]=useState({}); const [unavailable,setUnavailable]=useState([]);
  useEffect(()=>{let ignore=false;Promise.allSettled([documentStats(),maintenanceCatalog(),compliance("OISD-118"),patterns()]).then((results)=>{if(ignore)return;const keys=["documents","maintenance","audit","patterns"];const available={};const failed=[];results.forEach((result,index)=>{if(result.status==="fulfilled")available[keys[index]]=result.value;else failed.push(keys[index])});setSummary(available);setUnavailable(failed)});return()=>{ignore=true}},[]);
  const evidence = summary.maintenance?.equipment.flatMap((item)=>item.evidence.map((record)=>({...record,equipment_id:item.equipment_id}))).sort((left,right)=>right.date.localeCompare(left.date)).slice(0,4) ?? [];
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs uppercase tracking-[.2em] text-primary">Evidence-derived overview</p><h1 className="mt-2 text-2xl font-semibold">Command Centre</h1><p className="mt-1 text-sm text-text-secondary">All values below are returned by OPSIQ APIs from the current synthetic evidence corpus.</p></div><div className="flex items-center gap-2 self-start rounded-full border border-secondary/20 bg-secondary/5 px-3 py-2 text-xs text-secondary"><span className="h-2 w-2 rounded-full bg-secondary"/>Synthetic Demo</div></div>
    {unavailable.length>0&&<p className="rounded-lg border border-critical/30 bg-critical/5 p-4 text-sm text-critical">Unavailable dashboard sources: {unavailable.join(", ")}. Healthy API results remain visible; no cached or placeholder values are shown.</p>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Indexed chunks" value={summary.documents?.chunks??"…"} detail="Retrieval index API" icon={Files}/><MetricCard label="Assets with evidence" value={summary.maintenance?.equipment_count??"…"} detail="Unique work-order equipment IDs" icon={Activity} tone="text-secondary"/><MetricCard label="Compliance evidence" value={summary.audit?`${summary.audit.compliance_percentage}%`:"…"} detail="Synthetic OISD-118 only" icon={ShieldCheck} tone="text-warning"/><MetricCard label="High-risk assets" value={summary.maintenance?.high_risk_count??"…"} detail="Deterministic HIGH / CRITICAL" icon={TriangleAlert} tone="text-critical"/><MetricCard label="Pattern graph" value={summary.patterns?.knowledge_graph?.node_count??"…"} detail="Evidence-linked graph nodes" icon={Network}/></div>
    {summary.maintenance&&<div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Equipment recurrence risk</h2><div className="mt-4 space-y-3">{summary.maintenance.equipment.map((item)=><div className="grid grid-cols-[5rem_1fr_4rem] items-center gap-3 text-sm" key={item.equipment_id}><span className="font-mono text-primary">{item.equipment_id}</span><div className="h-2 rounded bg-border"><div className="h-full rounded bg-warning" style={{width:`${item.risk_score}%`}}/></div><span className="text-right">{item.risk_score}</span></div>)}</div></section><section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Latest work-order evidence</h2><div className="mt-4 divide-y divide-border">{evidence.map((record)=><div className="py-4" key={record.record_id}><p className="text-sm">{record.equipment_id} — {record.failure_type}</p><p className="mt-1 text-xs text-muted">{record.date} · {record.record_id} · {record.severity} · {record.downtime_hours} h</p></div>)}</div></section></div>}
  </div>;
}
