import { useEffect, useState } from "react";

import LoadingState from "../components/ui/LoadingState";
import { getApiErrorMessage, patterns } from "../services/api";

export default function FailurePatterns() {
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{let ignore=false;patterns().then((result)=>{if(!ignore)setData(result)}).catch((requestError)=>{if(!ignore)setError(getApiErrorMessage(requestError))}).finally(()=>{if(!ignore)setLoading(false)});return()=>{ignore=true}},[]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Failure Pattern Engine</h1><p className="text-sm text-text-secondary">Deterministic correlations across work orders and incident history; associations do not establish causality.</p></div>
    {loading&&<LoadingState message="Correlating evidence records..."/>}{!loading&&error&&<p className="rounded-lg border border-critical/30 bg-critical/5 p-4 text-sm text-critical">{error}</p>}
    {!loading&&data?.status==="ok"&&<><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-border bg-surface p-5"><p className="text-xs text-muted">Records analysed</p><p className="mt-2 text-3xl">{data.records_analyzed}</p></div><div className="rounded-xl border border-border bg-surface p-5"><p className="text-xs text-muted">Sources</p><p className="mt-2 text-sm">{Object.entries(data.source_counts).map(([name,count])=>`${name}: ${count}`).join(" · ")}</p></div><div className="rounded-xl border border-border bg-surface p-5"><p className="text-xs text-muted">Evidence graph</p><p className="mt-2 text-sm">{data.knowledge_graph.node_count} nodes · {data.knowledge_graph.edge_count} edges</p></div></div>
      <div className="grid gap-5 lg:grid-cols-2">{data.patterns.map((pattern)=><article className="rounded-xl border border-border bg-surface p-5" key={`${pattern.equipment_id}-${pattern.failure_type}`}><div className="flex justify-between"><div><p className="font-mono text-primary">{pattern.equipment_id}</p><h2 className="mt-2 font-semibold">{pattern.failure_type}</h2></div><span className={`text-xs ${pattern.risk==="CRITICAL"?"text-critical":"text-warning"}`}>{pattern.risk}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted">Observed range</dt><dd>{pattern.first_seen} → {pattern.last_seen}</dd></div><div><dt className="text-muted">Occurrences</dt><dd>{pattern.occurrences}</dd></div><div><dt className="text-muted">Sources</dt><dd>{pattern.sources.join(", ")}</dd></div><div><dt className="text-muted">Downtime</dt><dd>{pattern.cumulative_downtime_hours} h</dd></div></dl><p className="mt-4 break-words font-mono text-xs text-text-secondary">Evidence: {pattern.supporting_evidence_ids.join(", ")}</p></article>)}</div>
      <section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-semibold">Recurring cross-asset root causes</h2><div className="mt-4 space-y-3">{data.recurring_root_causes.map((item)=><div className="rounded-lg bg-card p-4 text-sm" key={item.value}><p>{item.value}</p><p className="mt-1 text-xs text-muted">{item.occurrences} records · {item.equipment_ids.join(", ")} · evidence {item.supporting_evidence_ids.join(", ")}</p></div>)}</div></section>
    </>}
  </div>;
}
