import { useEffect, useState } from "react";
import { Database, Eye, MonitorCog, ShieldCheck, UserPlus } from "lucide-react";
import { authRoles, authUsers, createAuthUser, getApiErrorMessage } from "../services/api";
import PageHeader from "../components/ui/PageHeader";
import Panel from "../components/ui/Panel";
import StatusBadge from "../components/ui/StatusBadge";

const posture = [
  [MonitorCog, "Environment", "Demonstration", "Synthetic operational data and simulated telemetry are always identified."],
  [Database, "Persistence", "SQLite + ChromaDB", "Operational records and document vectors persist at environment-configured volume paths."],
  [ShieldCheck, "Access control", "JWT + RBAC", "Access and refresh tokens enforce role-specific backend and frontend permissions."],
  [Eye, "Audit privacy", "Metadata only", "No prompts, secrets, passwords or raw payloads are retained in the audit trail."],
];
const initial = { username: "", display_name: "", password: "", role: "Operator" };

export default function SettingsPage() {
  const [users, setUsers] = useState([]), [roles, setRoles] = useState([]), [form, setForm] = useState(initial), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = async () => { try { const [userData, roleData] = await Promise.all([authUsers(), authRoles()]); setUsers(userData.users); setRoles(roleData.roles); } catch (requestError) { setError(getApiErrorMessage(requestError)); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await createAuthUser(form); setForm(initial); await load(); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setBusy(false); } };
  return <div className="space-y-6"><PageHeader eyebrow="Platform configuration" title="Settings & governance" description="Administrator-only identity management and runtime posture." actions={<StatusBadge tone="blue">RBAC enabled when configured</StatusBadge>} />{error ? <div role="alert" className="rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</div> : null}<div className="grid gap-4 md:grid-cols-2">{posture.map(([Icon, title, value, description]) => <Panel key={title}><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-primary/20 bg-primary/10 text-primary"><Icon size={18} /></span><div><p className="section-label">{title}</p><p className="mt-1 font-medium">{value}</p><p className="mt-2 text-sm leading-6 text-text-secondary">{description}</p></div></div></Panel>)}</div><Panel title="User administration" description="Create an identity with one least-privilege plant role. Passwords are stored only as salted scrypt hashes."><form onSubmit={submit} className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className="field" aria-label="Username" placeholder="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} required /><input className="field" aria-label="Display name" placeholder="Display name" value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })} required /><input className="field" type="password" minLength="12" aria-label="Temporary password" placeholder="Temporary password (12+ chars)" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><select className="field" aria-label="Role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}>{roles.map((role) => <option key={role}>{role}</option>)}</select><button className="primary-button justify-center" disabled={busy}><UserPlus size={16} />{busy ? "Creating..." : "Create user"}</button></form><div className="mt-5 overflow-x-auto"><table className="data-table w-full min-w-[640px]"><thead><tr><th>User</th><th>Display name</th><th>Role</th><th>Status</th><th>Created</th></tr></thead><tbody>{users.map((user) => <tr key={user.username}><td className="font-mono text-primary">{user.username}</td><td>{user.display_name}</td><td>{user.role}</td><td>{user.active ? "Active" : "Disabled"}</td><td className="font-mono text-xs">{new Date(user.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></Panel><Panel title="Industrial honesty"><ul className="grid gap-3 text-sm text-text-secondary md:grid-cols-2"><li>Not connected to SCADA, DCS or a plant historian.</li><li>Recurrence analytics are not certified failure prediction.</li><li>Compliance output is not legal certification.</li><li>Generated work orders require qualified engineer approval.</li></ul></Panel></div>;
}
